#!/usr/bin/env bash
# Transfers a file via ssh from client to server

filepath="$1"
ip_ad="$2"
username="$3"
sshkey="$4"

if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$sshkey" "$filepath" "$username"@"$ip_ad":~/
fi